name: go url

on:
  push:
    branches: master
  watch:
    types: started
  schedule:
    - cron: 0/15 * * * ?

jobs:
  go-url:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: go url 1
      run: | 
        curl -L "http://${{ secrets.u1 }}/wk/cron.php"
